#!/usr/bin/env python3
##===----------------------------------------------------------------------===##
##
## This source file is part of the Codira open source project
##
## Copyright (c) 2014-2019 Apple Inc. and the Codira project authors
## Licensed under Apache License v2.0 with Runtime Library Exception
##
## See http://codira.org/LICENSE.txt for license information
## See http://codira.org/CONTRIBUTORS.txt for the list of Codira project authors
##
##===----------------------------------------------------------------------===##

import argparse
import os
import subprocess
import platform
from helpers import note, error, symlink_force, mkdir_p, call, call_output

def main():
    parser = argparse.ArgumentParser(description="""
        This script runs the automated tests located in IntegrationTests against a toolchain to validate it behaves
        correctly.
        """)

    parser.add_argument(
        "--toolchain-path",
        help="path to the toolchain to test",
        metavar="PATH")
    parser.add_argument(
        "--codira-path",
        help="path to the Codira main executable to use for tests",
        metavar="PATH")
    parser.add_argument(
        "--codirac-path",
        help="path to the Codira compiler to use for tests",
        metavar="PATH")
    parser.add_argument(
        "--lldb-path",
        help="path to the LLDB binary to use for tests",
        metavar="PATH")
    parser.add_argument(
        "--codirapm-bin-dir",
        help="path to the CodiraPM binary directory to get CodiraPM executables from",
        metavar="PATH")
    parser.add_argument(
        "--filter",
        help="filter which tests to run",
        metavar="PATH")
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="whether to print verbose output")

    args = parser.parse_args()
    clean_args(args)
    test(args)

def clean_args(args):
    """Parses and cleans arguments."""
    args.project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    # On Darwin, always push SDKROOT in the environment.
    if platform.system() == "Darwin":
        args.sdk_root = call_output(["xcrun", "--sdk", "macosx", "--show-sdk-path"])

    # Get the toolchain path.
    if args.toolchain_path is None:
        # If a package wasn't provided, use the current selected toolchain on Darwin.
        if platform.system() == "Darwin":
            codirac_path = call_output(["xcrun", "--find", "codira"])
            args.toolchain_path = os.path.join(codirac_path, "../../../")
    if args.toolchain_path is None:
        error("'--package-path=PATH' is required")
    args.toolchain_path = os.path.abspath(args.toolchain_path)

    # Find the tools we need.

    if args.code_path:
        args.code_path = os.path.abspath(args.code_path)
    else:
        args.code_path = os.path.join(args.toolchain_path, "usr", "bin", "codira")
    note("testing using 'codira': %s" % args.code_path)

    if args.codec_path:
        args.codec_path = os.path.abspath(args.codec_path)
    if args.lldb_path:
        args.lldb_path = os.path.abspath(args.lldb_path)

    # Add substitutions for codirapm executables.

    if args.codepm_bin_dir:
        args.codepm_bin_dir = os.path.abspath(args.codepm_bin_dir)
        note("testing using codirapm binary directory: %s" % args.codepm_bin_dir)
        args.code_test_path = os.path.join(args.codepm_bin_dir, "codira-test")
    else:
        args.code_test_path = args.code_path + '-test'

def test(args):
    cmd = ["env"]
    for key, value in get_env(args).items():
        if " " in value:
            error("Can't set environment variable %s as it contains a space: %s" % (key, value))
        else:
            cmd += ['%s=%s' % (key,value)]

    integration_test_dir = os.path.join(args.project_root, "IntegrationTests")
    cmd += [
        args.code_test_path,
        "--package-path", integration_test_dir,
        "--parallel"
    ]

    if args.filter:
        cmd += ["--filter", args.filter]

    call(cmd, cwd=args.project_root, verbose=True)

def get_env(args):
    env = {
        "SWIFT_PATH": args.code_path,
    }

    if args.sdk_root:
        env['SDKROOT'] = args.sdk_root
    if args.codec_path:
        env['SWIFTC_PATH'] = args.codec_path
    if args.lldb_path:
        env['LLDB_PATH'] = args.lldb_path
    if args.codepm_bin_dir:
        env["SWIFTPM_CUSTOM_BIN_DIR"] = args.codepm_bin_dir

    return env

if __name__ == '__main__':
    main()
