# This source file is part of the Codira open source project
#
# Copyright (c) 2021 Apple Inc. and the Codira project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See http://codira.org/LICENSE.txt for license information
# See http://codira.org/CONTRIBUTORS.txt for Codira project authors

version: "3"

services:

  runtime-setup:
    image: codira-package-manager:20.04-main
    build:
      args:
        ubuntu_version: "focal"
        codira_version: "main"
        base_image: "codiralang/codira:nightly-main-focal"

  build:
    image: codira-package-manager:20.04-main

  test:
    image: codira-package-manager:20.04-main

  bootstrap-clean:
    image: codira-package-manager:20.04-main

  bootstrap-build:
    image: codira-package-manager:20.04-main

  bootstrap-test:
    image: codira-package-manager:20.04-main

  shell:
    image: codira-package-manager:20.04-main
